[package]
name = "benches"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[dependencies]
wasmi = { path = ".." }
assert_matches = "1.2"
wabt = "0.6"

[profile.bench]
debug = true
